# Generated by Django 4.2 on 2023-08-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImage', models.ImageField(upload_to='slider/')),
                ('slidetitle', models.CharField(max_length=50)),
                ('titleheader', models.CharField(max_length=20)),
                ('titlebottom', models.CharField(max_length=20)),
                ('firstbuttontitle', models.CharField(max_length=20)),
                ('secoundbuttontitle', models.CharField(max_length=20)),
            ],
        ),
    ]
