# Generated by Django 4.2 on 2023-08-07 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProductTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OurProductsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(upload_to='Related/')),
                ('productname', models.CharField(max_length=100)),
                ('prodcutdiscountprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=90)),
                ('productoriginalprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=90)),
                ('productdescriptopm', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.ourproducttitle')),
            ],
        ),
    ]
