# Generated by Django 4.2.4 on 2023-08-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImage', models.ImageField(upload_to='sliderimage/')),
                ('slideheader', models.CharField(max_length=40)),
                ('firsttitle', models.CharField(max_length=70)),
                ('secoundtitle', models.CharField(max_length=80)),
                ('productname', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
    ]
