# Generated by Django 4.2 on 2023-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_user_alter_slider_firstbuttontitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImage', models.ImageField(upload_to='special_slider/')),
                ('slideHeader', models.CharField(max_length=30)),
                ('firsttitle', models.CharField(max_length=30)),
                ('secoundtitle', models.CharField(max_length=30)),
                ('productName', models.CharField(max_length=40)),
                ('productDiscountPrice', models.DecimalField(decimal_places=2, max_digits=90)),
                ('productOriginalPrice', models.DecimalField(decimal_places=2, max_digits=90)),
                ('Buttontext', models.CharField(max_length=20)),
            ],
        ),
    ]
