# Generated by Django 4.2 on 2023-08-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_ourproducttitle_ourproductslist'),
    ]

