# Generated by Django 4.2 on 2023-08-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_specialslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogImage', models.ImageField(upload_to='blog/')),
                ('blogheader', models.CharField(max_length=50)),
                ('blogeradminImage', models.ImageField(upload_to='blog/admin/')),
                ('blogditails', models.TextField(max_length=500)),
            ],
        ),
    ]
