# Generated by Django 4.2 on 2023-08-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_delete_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolloUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instaImage', models.ImageField(upload_to='insta/')),
            ],
        ),
    ]
