# Generated by Django 4.2 on 2023-08-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_follous'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(upload_to='SpecialOffer/')),
                ('text1', models.CharField(max_length=30)),
                ('text2', models.CharField(max_length=30)),
                ('text3', models.CharField(max_length=30)),
                ('text4', models.CharField(max_length=30)),
                ('boldtext', models.CharField(max_length=30)),
                ('productname', models.CharField(max_length=50)),
                ('productprice', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('productamount', models.CharField(max_length=50)),
            ],
        ),
    ]
