# Generated by Django 4.2 on 2023-08-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='postdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
