# Generated by Django 4.2 on 2023-08-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_specialoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subcattegorry', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
                ('subcategory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.BooleanField(default=False)),
                ('productimage', models.ImageField(upload_to='toprelatedProduct/')),
                ('productcategory', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('productDiscountprice', models.DecimalField(decimal_places=2, max_digits=90)),
                ('productOriginalprice', models.DecimalField(decimal_places=2, max_digits=90)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task1.category')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('twitterlink', models.CharField(max_length=100)),
                ('facebooklink', models.CharField(max_length=100)),
                ('youtubelink', models.CharField(max_length=100)),
                ('instagramlink', models.CharField(max_length=100)),
                ('linkdeinlink', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=50)),
                ('availableTime', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='ourproductslist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='related',
            name='category',
        ),
        migrations.DeleteModel(
            name='TopRatedProducts',
        ),
        migrations.DeleteModel(
            name='OurProductsList',
        ),
        migrations.DeleteModel(
            name='OurProductTitle',
        ),
        migrations.DeleteModel(
            name='ProductsCategory',
        ),
        migrations.DeleteModel(
            name='Related',
        ),
    ]
