# Generated by Django 4.2 on 2023-08-08 21:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_category_products_websitesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producttitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
