# Generated by Django 4.2 on 2023-08-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_dealsoftheday'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopRatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productimage', models.ImageField(upload_to='toprelatedProduct/')),
                ('productcategory', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('productDiscountprice', models.DecimalField(decimal_places=2, max_digits=90)),
                ('productOriginalprice', models.DecimalField(decimal_places=2, max_digits=90)),
            ],
        ),
    ]
