# Generated by Django 4.2 on 2023-08-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_products_producttitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='producttitle',
        ),
    ]
