# Generated by Django 4.2 on 2023-08-08 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0008_remove_products_producttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productDiscription',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
