# Generated by Django 4.2 on 2023-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0008_topratedproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerimage', models.ImageField(upload_to='banner/')),
                ('firstline', models.CharField(max_length=50)),
                ('secoundline', models.CharField(max_length=50)),
                ('thirdline', models.CharField(max_length=50)),
                ('fourthline', models.CharField(max_length=50)),
            ],
        ),
    ]
