# Generated by Django 4.2 on 2023-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0011_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=55)),
                ('username', models.CharField(max_length=30)),
                ('password1', models.CharField(max_length=35)),
                ('password2', models.CharField(max_length=35)),
            ],
        ),
    ]
