# Generated by Django 4.2 on 2023-08-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0013_productscategory_toprated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopRated',
            new_name='Related',
        ),
    ]
