# Generated by Django 4.2 on 2023-08-05 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0014_rename_toprated_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='related',
            name='productimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Related/'),
            preserve_default=False,
        ),
    ]
