# Generated by Django 4.2 on 2023-08-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0015_related_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='bannerMovinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movingimage', models.ImageField(upload_to='moveimage/')),
            ],
        ),
    ]
